### ISSUE TITLE
Calls not Start | Missing Event Trigger

### ISSUE THREAD

**Issue by Llama-Palooza** [Lanzaned-Enterprises/LENT-Megaphone#1]
This event doesn't get called anywhere in the script so no calls ever get send to the selected workers.
![image](https://github.com/Lanzaned-Enterprises/LENT-Megaphone/assets/124511433/34ce3525-df1a-4fd7-bc84-a0fbb327c6d3)
After doing the command `aicalls LS`, nothing ever happens.

**Comment by SerenaKing** [comment]
Open issue in the right repository
